---
- hosts: localhost
  become: true

  tasks:
    - name: Get host IP address.
      shell: "/sbin/ip route | awk '/default/ { print $3 }'"
      register: host_ip
      changed_when: false

    - name: Set host_ip_address variable.
      set_fact:
        host_ip_address: "{{ host_ip.stdout }}"

    - name: Copy Flask app into place.
      template:
        src: /etc/ansible/api.py.j2
        dest: /opt/www/api.py
        mode: 0755